-- 1231.9
--총 연습문제 1~4

DROP TABLE CUSTOMER;
DROP TABLE CUS_LEVEL;


CREATE TABLE CUS_LEVEL(
    LEVELNO   NUMBER(20) PRIMARY KEY,
    LEVELNAME VARCHAR2(20) NOT NULL);

CREATE SEQUENCE CUS_SQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9999
    MINVALUE 1
    NOCYCLE
    NOCACHE;

CREATE TABLE CUSTOMER(
    CNO      NUMBER(3)    PRIMARY KEY,
    CNAME    VARCHAR2(50) NOT NULL,
    JOINDATE DATE         DEFAULT SYSDATE,
    PHONE    VARCHAR2(20) UNIQUE,
    POINT    NUMBER(5),
    LEVELNO  NUMBER(10) REFERENCES CUS_LEVEL(LEVELNO));


INSERT INTO CUS_LEVEL VALUES(1,'VVIP');
INSERT INTO CUS_LEVEL VALUES(2,'VIP');
INSERT INTO CUS_LEVEL VALUES(3,'NORMAL');
INSERT INTO CUS_LEVEL VALUES(4,'BLACK');


INSERT INTO CUSTOMER 
    VALUES(CUS_SQ.NEXTVAL,'홍길동',TO_DATE('17/10/17','YYMMDD'),'010-9999-9999',300,1);
INSERT INTO CUSTOMER 
    VALUES(CUS_SQ.NEXTVAL,'이철수',TO_DATE('17/11/12','YYYYMMDD'),'010-8888-8888',NULL,2);    

SELECT * FROM CUSTOMER;

SELECT * FROM CUS_LEVEL;
DESC CUS_LEVEL;
DESC CUSTOMER;


--연습문제 5.위와 같은 두개의 테이블을 이용하여 아래와 같이 출력하는 SQL문도 작성하시오 (1231.9노트 맨 마지막)
SELECT CNO, CNAME, TO_CHAR(JOINDATE,'YYYY-MM-DD'), PHONE, POINT, LEVELNAME
    FROM CUSTOMER C, CUS_LEVEL L
    WHERE L.LEVELNO = C.LEVELNO;

