-- [IX] SEQUENCE: 순차번호 생성기, 대부분 인위적인 PK사용 용도  
DROP SEQUENCE FRIEND_SEQ; --있는 SEQUENCE그대로 쓰면 1번부터 시작하지 않아 
CREATE SEQUENCE FRIEND_SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9999
    MINVALUE 1
    NOCYCLE 
    NOCACHE; --매번킬때 1부터 

DROP TABLE FRIEND;  --혹시 해당 테이블 있을까봐
CREATE TABLE FRIEND(
    NUM   NUMBER(4) PRIMARY KEY, --MAX가9999이므로 NUMBER 4넘을필요없음
    NAME  VARCHAR2(30) NOT NULL,
    PHONE VARCHAR2(20) UNIQUE, --UNIQUE:유일, NULL허용 
    TEL   VARCHAR2(20),
    LAST_MODIFYED DATE);



