--12. 물품을 주문한 고객에게 다음 보기와 같은 주문서를 메일로 발송할 수 있는 쇼핑몰의 요구조건을 만족할 수 있도록 데이터베이스 설계를 하시오 
--(단 회원가입시 주소와 전화번호는 주문시 배송주소와 배송지 전화번호와 다를 수 있다.)
--12-1 ERD 설계 갭쳐화면 12.png
--12-2 ERD 설계에 맞는 테이블을 생성하는 DDL문 작성한 SQL파일: 13.sql

DROP TABLE CUSTOMER;
CREATE TABLE CUSTOMER(
    CUS_ID   VARCHAR2(20) PRIMARY KEY,
    EMAIL    VARCHAR2(20) NOT NULL,
    CUS_NAME VARCHAR2(20) NOT NULL,
    ADDRESS  VARCHAR2(255)NOT NULL,
    TEL      VARCHAR2(20) NOT NULL );

SELECT * FROM CUSTOMER;


CREATE TABLE PRODUCT(
    PRODUCT_CODE  VARCHAR2(5)  PRIMARY KEY,
    PRODUCT_NAME  VARCHAR2(20) NOT NULL,
    PRODUCT_PRICE NUMBER(20)   NOT NULL,
    PRODUCT_STOCK VARCHAR2(20) NOT NULL);

SELECT * FROM PRODUCT;

CREATE SEQUENCE CART_SEQ
    MAXVALUE 9999
    NOCYCLE
    NOCACHE;

CREATE TABLE CART(
    CART_SEQUENCE   NUMBER(20)   PRIMARY KEY,
    CUS_ID          VARCHAR2(20) REFERENCES CUSTOMER(CUS_ID),
    PRODUCT_CODE    VARCHAR2(5)  REFERENCES PRODUCT(PRODUCT_CODE),
    SELECTED_NUMBER VARCHAR2(5)  NOT NULL,
    PRODUCT_PRICE   NUMBER(20)   NOT NULL);


CREATE SEQUENCE ORDER_SEQ
    MAXVALUE 9999
    NOCYCLE
    NOCACHE;

CREATE TABLE ORDER_DETAIL(
    ODER_ID NUMBER(20)         PRIMARY KEY,
    CUS_ID  VARCHAR2(20)       REFERENCES CUSTOMER(CUS_ID),
    ORDER_DATE    VARCHAR2(20) DEFAULT SYSDATE,
    TEL     VARCHAR2(20)       NOT NULL,
    ADDRESS VARCHAR2(255)      NOT NULL);


CREATE TABLE ORDER_TABLE(
    ORDER_SEQUENCE   NUMBER(20)  PRIMARY KEY,
    ORDER_NO         NUMBER(20)  REFERENCES ORDER_DETAIL(ORDER_NO),
    PRODUCT_CODE     VARCHAR2(5) REFERENCES PRODUCT(PRODUCT_CODE),
    PURCHASED_NUMBER NUMBER(20)  NOT NULL,
    PRODUCT_PRICE    NUMBER(20)  NOT NULL);





