CREATE TABLE MEMBER(
   NAME      VARCHAR(20)   NOT NULL,
   PHONE     VARCHAR(20)   NOT NULL,
   EMAIL     VARCHAR(30)   NOT NULL,
   AGE       NUMBER(9)     NOT NULL,
   GRADE     NUMBER(5)     NOT NULL,
   ETC       VARCHAR(20)   
);