SELECT * FROM DEPT ;
SELECT * FROM EMP;

--JAVA¿¡ ¾µ QUERY
UPDATE DEPT SET DNAME = 'IT', LOC = 'BUSAN'
    WHERE DEPTNO = 50;
COMMIT;
SELECT * FROM DEPT WHERE DEPTNO=50;
DELETE FROM DEPT WHERE DEPTNO=60;
ROLLBACK;
INSERT INTO DEPT VALUES (70,'FINANCE', 'SEATTLE');
COMMIT; 

SELECT EMPNO,ENAME,JOB,SAL
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO 
    AND DNAME = 'SALES';




    
    
    
    