DROP TABLE JOB;
DROP TABLE PERSON;
CREATE SEQUENCE JOB_SQ
    MAXVALUE 9999
    NOCYCLE
    NOCACHE;


CREATE TABLE JOB(
    JNO NUMBER(2) PRIMARY KEY,
    JNAME VARCHAR2(30)); 
SELECT * FROM JOB;



CREATE SEQUENCE PERSON_SQ
    MAXVALUE 9999
    NOCYCLE
    NOCACHE;

CREATE TABLE PERSON(
    NO NUMBER(5) PRIMARY KEY,
    NAME VARCHAR2(30),
    JNO NUMBER(2) REFERENCES JOB(JNO),
    KOR NUMBER(3),
    ENG NUMBER(3),
    MATH NUMBER(3));

SELECT * FROM PERSON;   

--1.입력
INSERT INTO JOB VALUES (10,'배우');
INSERT INTO JOB VALUES (20,'가수');
    
INSERT INTO PERSON VALUES (PERSON_SQ.NEXTVAL,'정우성',
                    (SELECT JNO FROM JOB WHERE JNAME='배우'),90,80,81);
INSERT INTO PERSON VALUES (PERSON_SQ.NEXTVAL,'박세영',
                    (SELECT JNO FROM JOB WHERE JNAME='배우'),80,90,80);       
INSERT INTO PERSON VALUES (PERSON_SQ.NEXTVAL,'배수지',
                    (SELECT JNO FROM JOB WHERE JNAME='가수'),80,90,80);   
INSERT INTO PERSON VALUES (PERSON_SQ.NEXTVAL,'설현',
                    (SELECT JNO FROM JOB WHERE JNAME='가수'),80,90,80);   
INSERT INTO PERSON VALUES (PERSON_SQ.NEXTVAL,'송혜교',
                    (SELECT JNO FROM JOB WHERE JNAME='배우'),80,90,80);   
                    
-- 2: 1 송해교(5번)  배우      100    	100    100	 300 (총점순으로 내림차순)

SELECT NAME || '( '||NO||' 번)' NAME, JNAME, KOR, ENG, MATH,
    KOR+ENG+MATH SUM
    FROM PERSON P, JOB J
    WHERE P.JNO = J.JNO AND JNAME = '배우'
    ORDER BY SUM DESC; -- FROM절에 들어갈 서브쿼리

SELECT ROWNUM RANK, S.*
    FROM(SELECT NAME || '( '||NO||' 번)' NAME, JNAME, KOR, ENG, MATH,
    KOR+ENG+MATH SUM
    FROM PERSON P, JOB J
    WHERE P.JNO = J.JNO AND JNAME = '배우'
    ORDER BY SUM DESC) S; -- 자바에 2번 기능에 쓸 쿼리 

--3번 기능
SELECT ROWNUM RANK, S.*
    FROM(SELECT NAME || '( '||NO||' 번)' NAME, JNAME, KOR, ENG, MATH,
    KOR+ENG+MATH SUM
    FROM PERSON P, JOB J
    ORDER BY SUM DESC) S; 

COMMIT;

-- combobox에 넣을 직업 리스트
SELECT JNAME FROM JOB;           -- persondao에 넣어






